apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-cifs
  resources:
    requests:
      storage: 10Gi
