apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
  namespace: default
type: Opaque
stringData:
  # Keys required by csi-driver-smb
  username: "REPLACE_SMB_USER"
  password: "REPLACE_SMB_PASSWORD"
